== Postdeployment steps
. https://manage.xqmsg.com/login[Sign in to XQ^].

. Update the range of trusted IP addresses.
.. In the navigation pane, choose *IP Ranges*.
.. Choose the tag for the address range that you created in the predeployment steps, for example, `Site-to-AWS`.
.. Add the publicly accessible IP address of the deployed EC2 instance.

. Configure the newly created gateway.
.. In the navigation pane, choose *Gateways*.
.. Choose the gateway that you named in the predeployment steps, for example, `AWS-Gateway`.
.. Enter the public IPV4 address (*Connection IP*) and any local IP addresses (*Gateway Local IPs*) of the deployed EC2 instance.
.. Enter or choose the following for the inbound route:
* *Name* (for example, `AWS-Gateway-Inbound`)
* *Protocol* (match the on-site encryption gateway)
* *Algorithm* (match the on-site encryption gateway)
* *Listen IP* (0.0.0.0)
* *Listen Port* (the previously entered publicly accessible port that was generated through the Partner Solution)
.. Enter the EC2 instance's Elastic IP address. To find it, look at the EC2 instance in the AWS Management Console or refer to the AWS CloudFormation outputs for the Partner Solution stack.
